# Generated by Django 6.0.8 on 2026-09-14 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('format', models.CharField(choices=[('png', 'PNG'), ('jpeg', 'JPEG'), ('pdf', 'PDF')], max_length=20)),
                ('quality', models.IntegerField(default=90)),
                ('page_range', models.CharField(default='all', max_length=100)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('file_url', models.URLField(blank=True, default='')),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exports', to='designs.design')),
            ],
            options={
                'db_table': 'export_jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
