# Generated by Django 6.0.8 on 2026-09-14 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designpage',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='designs.design'),
        ),
        migrations.AddField(
            model_name='designversion',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='designversion',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='designs.design'),
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['owner', 'status'], name='designs_owner_i_59d1d5_idx'),
        ),
        migrations.AddIndex(
            model_name='design',
            index=models.Index(fields=['owner', 'updated_at'], name='designs_owner_i_8be232_idx'),
        ),
        migrations.AddIndex(
            model_name='designpage',
            index=models.Index(fields=['design', 'page_number'], name='design_page_design__378210_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='designpage',
            unique_together={('design', 'page_number')},
        ),
        migrations.AddIndex(
            model_name='designversion',
            index=models.Index(fields=['design', 'version_number'], name='design_vers_design__30022a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='designversion',
            unique_together={('design', 'version_number')},
        ),
    ]
