# Generated by Django 6.0.8 on 2026-09-14 16:22

import apps.designs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designpage',
            name='document',
            field=models.JSONField(default=apps.designs.models.empty_dict),
        ),
    ]
