# Generated by Django 6.0.8 on 2026-09-27 09:26

import apps.designs.documents
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("designs", "0003_alter_designpage_document"),
        # The raw SQL below rewrites the `design_id` columns of tables owned by
        # these apps, so their migrations must have run first.
        ("assets", "0002_initial"),
        ("exports", "0001_initial"),
        ("sharing", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="designpage",
            unique_together=None,
        ),
        migrations.RemoveIndex(
            model_name="designpage",
            name="design_page_design__378210_idx",
        ),
        migrations.RenameField(
            model_name="design",
            old_name="current_version",
            new_name="revision",
        ),
        migrations.AddField(
            model_name="design",
            name="document",
            field=models.JSONField(
                default=apps.designs.documents.build_default_document
            ),
        ),
        migrations.AddField(
            model_name="design",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="design",
            name="is_template",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="design",
            name="last_opened_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="design",
            name="schema_version",
            field=models.CharField(default="1.0", max_length=20),
        ),
        migrations.AddField(
            model_name="design",
            name="thumbnail_key",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        # Safely convert integer primary keys to UUIDs for `designs` and
        # `design_versions` without attempting an invalid cast. The strategy:
        # 1. Ensure `pgcrypto` is available for `gen_random_uuid()`.
        # 2. Add `new_id uuid` to designs and design_versions and populate it.
        # 3. Add `new_design_id` uuid to all tables that reference designs and populate.
        # 4. Drop FK constraints that reference `designs` and swap old/new id columns.
        # 5. Recreate PK and FK constraints against the new UUID columns.
        # The reverse is intentionally a no-op because reversing UUID migration is unsafe.
        migrations.RunSQL(
            sql='''BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

-- Add new uuid columns on designs and design_versions
ALTER TABLE designs ADD COLUMN IF NOT EXISTS new_id uuid DEFAULT gen_random_uuid();
UPDATE designs SET new_id = gen_random_uuid() WHERE new_id IS NULL;
ALTER TABLE design_versions ADD COLUMN IF NOT EXISTS new_id uuid DEFAULT gen_random_uuid();
UPDATE design_versions SET new_id = gen_random_uuid() WHERE new_id IS NULL;

-- Add and populate mapping columns on all referencing tables
ALTER TABLE export_jobs ADD COLUMN IF NOT EXISTS new_design_id uuid;
UPDATE export_jobs SET new_design_id = d.new_id FROM designs d WHERE export_jobs.design_id = d.id;

ALTER TABLE asset_usage ADD COLUMN IF NOT EXISTS new_design_id uuid;
UPDATE asset_usage SET new_design_id = d.new_id FROM designs d WHERE asset_usage.design_id = d.id;

ALTER TABLE design_shares ADD COLUMN IF NOT EXISTS new_design_id uuid;
UPDATE design_shares SET new_design_id = d.new_id FROM designs d WHERE design_shares.design_id = d.id;

ALTER TABLE design_pages ADD COLUMN IF NOT EXISTS new_design_id uuid;
UPDATE design_pages SET new_design_id = d.new_id FROM designs d WHERE design_pages.design_id = d.id;

ALTER TABLE design_versions ADD COLUMN IF NOT EXISTS new_design_id uuid;
UPDATE design_versions SET new_design_id = d.new_id FROM designs d WHERE design_versions.design_id = d.id;

-- Drop foreign key constraints that reference designs (dynamic)
DO $$ DECLARE r record; BEGIN
  FOR r IN SELECT conname, conrelid::regclass::text AS tbl FROM pg_constraint WHERE contype='f' AND confrelid = 'designs'::regclass LOOP
    EXECUTE format('ALTER TABLE %s DROP CONSTRAINT IF EXISTS %I;', r.tbl, r.conname);
  END LOOP;
END $$;

-- Swap designs primary key: id (int) -> new_id (uuid)
ALTER TABLE designs DROP CONSTRAINT IF EXISTS designs_pkey;
ALTER TABLE designs RENAME COLUMN id TO old_id;
ALTER TABLE designs RENAME COLUMN new_id TO id;
ALTER TABLE designs ADD PRIMARY KEY (id);

-- Swap referencing columns to point to new UUIDs
ALTER TABLE export_jobs RENAME COLUMN design_id TO old_design_id;
ALTER TABLE export_jobs RENAME COLUMN new_design_id TO design_id;

ALTER TABLE asset_usage RENAME COLUMN design_id TO old_design_id;
ALTER TABLE asset_usage RENAME COLUMN new_design_id TO design_id;

ALTER TABLE design_shares RENAME COLUMN design_id TO old_design_id;
ALTER TABLE design_shares RENAME COLUMN new_design_id TO design_id;

ALTER TABLE design_pages RENAME COLUMN design_id TO old_design_id;
ALTER TABLE design_pages RENAME COLUMN new_design_id TO design_id;

ALTER TABLE design_versions RENAME COLUMN design_id TO old_design_id;
ALTER TABLE design_versions RENAME COLUMN new_design_id TO design_id;

-- Recreate foreign keys to designs(id)
ALTER TABLE export_jobs ADD CONSTRAINT export_jobs_design_id_fkey FOREIGN KEY (design_id) REFERENCES designs(id) ON DELETE CASCADE;
ALTER TABLE asset_usage ADD CONSTRAINT asset_usage_design_id_fkey FOREIGN KEY (design_id) REFERENCES designs(id) ON DELETE CASCADE;
ALTER TABLE design_shares ADD CONSTRAINT design_shares_design_id_fkey FOREIGN KEY (design_id) REFERENCES designs(id) ON DELETE CASCADE;
ALTER TABLE design_pages ADD CONSTRAINT design_pages_design_id_fkey FOREIGN KEY (design_id) REFERENCES designs(id) ON DELETE CASCADE;
ALTER TABLE design_versions ADD CONSTRAINT design_versions_design_id_fkey FOREIGN KEY (design_id) REFERENCES designs(id) ON DELETE CASCADE;

-- Now convert design_versions primary key from integer to uuid (swap id <-> new_id)
ALTER TABLE design_versions DROP CONSTRAINT IF EXISTS design_versions_pkey;
ALTER TABLE design_versions RENAME COLUMN id TO old_id;
ALTER TABLE design_versions RENAME COLUMN new_id TO id;
ALTER TABLE design_versions ADD PRIMARY KEY (id);

COMMIT;
''',
            reverse_sql=migrations.RunSQL.noop,
        ),

        migrations.AddIndex(
            model_name="design",
            index=models.Index(
                fields=["owner", "is_deleted"], name="designs_owner_i_11dda1_idx"
            ),
        ),
        migrations.DeleteModel(
            name="DesignPage",
        ),
    ]
