# Generated by Django 6.0.8 on 2026-09-14 16:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('designs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetusage',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage', to='assets.asset'),
        ),
        migrations.AddField(
            model_name='assetusage',
            name='design',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='designs.design'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['owner', 'created_at'], name='assets_owner_i_47e184_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assetusage',
            unique_together={('asset', 'design')},
        ),
    ]
