# Generated by Django 6.0.8 on 2026-10-02 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='url',
        ),
    ]
