# Generated by Django 6.0.8 on 2026-09-14 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("social_media", "Social Media"),
                            ("marketing", "Marketing"),
                            ("presentation", "Presentation"),
                            ("poster", "Poster"),
                            ("flyer", "Flyer"),
                            ("business", "Business"),
                        ],
                        max_length=20,
                    ),
                ),
                ("preview_url", models.URLField(blank=True, default="")),
                ("document", models.JSONField()),
                ("is_public", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "templates",
                "ordering": ["-created_at"],
            },
        ),
    ]
