# Generated by Django 6.0.8 on 2026-09-14 16:25

import apps.sharing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DesignShare",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "token",
                    models.CharField(
                        default=apps.sharing.models.generate_share_token,
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "permission",
                    models.CharField(
                        choices=[("view", "View Only"), ("edit", "Can Edit")],
                        default="view",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "design_shares",
                "ordering": ["-created_at"],
            },
        ),
    ]
